matrix:
  include:
    - language: node_js
      node_js: '12'
      cache: yarn
    - language: node_js
      node_js: '10'
      cache: yarn
    - language: node_js
      node_js: '8'
      cache: yarn
script: yarn test:ci