language: node_js
cache: yarn
jobs:
  include:
    - stage: prepare cache
      script: true
      node_js: '10'

    - stage: test
      script: yarn lint:ci && yarn test:ci
      node_js: '12.9'
    - stage: test
      script: yarn lint:ci && yarn test:ci
      node_js: '10'
    - stage: test
      script: yarn lint:ci && yarn test:ci
      node_js: '8'

    - stage: test arm
      node_js: '10'
      services:
        - docker
      script:
        - ./bin/docker-test.sh
stages:
  - prepare cache
  - test
  - test arm
